### ISSUE TITLE
old boltdb

### ISSUE THREAD

**Issue by joe-getcouragenow** [clintjedwards/basecoat#56]
Came here for the bleve stuff but noticed that your using the old BoltDB.
Curious why ? Or just that "aint broke, so wont fix it " ?

**Comment by clintjedwards** [comment]
Ah, you mean why use the original instead of the CoreOs fork?

Yeah "If it aint broke..." sums it up well enough here. The original is pretty solid enough, especially for a small project like this one. I'm not overly familiar with the CoreOS version and what has been added, but I really just needed a simple local key/value which has no surprises and the original works well for that.
